sudo: false
language: node_js
node_js:
  - "4"
  - "5"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4006bbb5d24d1b690394
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
